In [74]:
import pandas as pd
import numpy as np

In [75]:
df10 = pd.read_csv('data/JT_SHP_SALES_VARTION_LIST_202210.csv')

In [76]:
df10

,ANALS_YM,CMPNM_NM,SIGNGU_NM,ADSTRD_NM,AREA_NM,MLSFC_NM,SCLAS_NM,JJINHBT_SALES_PRICE_RATE,JJINHBT_SALES_CO_RATE,OTSD_SALES_PRICE_RATE,OTSD_SALES_CO_RATE,ALL_SALES_PRICE_RATE,ALL_SALES_CO_RATE,VARTION_RT,RANK_CO,GID_ID
0,202210,한국맥도날드(유)제주탑동점,제주시,건입동,제주시내,패스트푸드,햄버거,9.99,35.30,0.33,8.41,1.02,19.61,-2.82,12999,다다09b03a
1,202210,모드락탑동점,제주시,건입동,제주시내,한식,단품요리 전문,3.60,4.72,0.60,4.80,0.84,5.66,-0.42,11946,다다09a03a
2,202210,산지해장국,제주시,건입동,제주시내,한식,해장국,3.06,4.23,0.49,4.18,0.69,4.97,-1.20,12854,다다09b03a
3,202210,고집돌우럭,제주시,건입동,제주시내,한식,회,1.02,0.38,1.85,4.05,1.89,3.49,-0.35,11668,다다09b03a
4,202210,주식회사 제이에스디비,제주시,건입동,제주시내,한식,단품요리 전문,1.45,3.88,0.17,2.73,0.26,3.65,-0.90,12734,다다09b03a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13036,202210,술창고,서귀포시,효돈동,서귀포시내,주점및주류판매,맥주/요리주점,0.16,0.11,0.00,0.00,0.01,0.04,-0.04,5584,다나17b75a
13037,202210,하효마을회떡방앗간,서귀포시,효돈동,서귀포시내,간식,떡/한과,0.10,0.11,0.00,0.00,0.01,0.04,-0.02,4355,다나17b74b
13038,202210,하준정식,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.03,0.00,0.00,0.00,0.01,0.01,2474,다나17b75a
13039,202210,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,0.00,0.03,-0.01,3508,다나17b75a
13040,202210,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.01,0.03,0.00,0.00,0.00,0.01,0.02,2062,다나17b75a

In [77]:
df10 = df10.rename(columns={'ANALS_YM' : '분석년월', 'CMPNM_NM' : '음식점명', 'SIGNGU_NM' : '시군구명', 'ADSTRD_NM' : '행정동명',
                   'AREA_NM' : '지역명', 'MLSFC_NM' : '중분류', 'SCLAS_NM' : '소분류', 'JJINHBT_SALES_PRICE_RATE' : '10월현지인매출금액',
                   'JJINHBT_SALES_CO_RATE' : '10월현지인매출수', 'OTSD_SALES_PRICE_RATE' : '10월외지인매출금액', 'OTSD_SALES_CO_RATE' : '10월외지인매출수', 'ALL_SALES_PRICE_RATE' : '10월전체매출금액비율',
                   'ALL_SALES_CO_RATE' : '10월전체매출수비율'})

In [78]:
df10

,분석년월,음식점명,시군구명,행정동명,지역명,중분류,소분류,10월현지인매출금액,10월현지인매출수,10월외지인매출금액,10월외지인매출수,10월전체매출금액비율,10월전체매출수비율,VARTION_RT,RANK_CO,GID_ID
0,202210,한국맥도날드(유)제주탑동점,제주시,건입동,제주시내,패스트푸드,햄버거,9.99,35.30,0.33,8.41,1.02,19.61,-2.82,12999,다다09b03a
1,202210,모드락탑동점,제주시,건입동,제주시내,한식,단품요리 전문,3.60,4.72,0.60,4.80,0.84,5.66,-0.42,11946,다다09a03a
2,202210,산지해장국,제주시,건입동,제주시내,한식,해장국,3.06,4.23,0.49,4.18,0.69,4.97,-1.20,12854,다다09b03a
3,202210,고집돌우럭,제주시,건입동,제주시내,한식,회,1.02,0.38,1.85,4.05,1.89,3.49,-0.35,11668,다다09b03a
4,202210,주식회사 제이에스디비,제주시,건입동,제주시내,한식,단품요리 전문,1.45,3.88,0.17,2.73,0.26,3.65,-0.90,12734,다다09b03a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13036,202210,술창고,서귀포시,효돈동,서귀포시내,주점및주류판매,맥주/요리주점,0.16,0.11,0.00,0.00,0.01,0.04,-0.04,5584,다나17b75a
13037,202210,하효마을회떡방앗간,서귀포시,효돈동,서귀포시내,간식,떡/한과,0.10,0.11,0.00,0.00,0.01,0.04,-0.02,4355,다나17b74b
13038,202210,하준정식,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.03,0.00,0.00,0.00,0.01,0.01,2474,다나17b75a
13039,202210,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,0.00,0.03,-0.01,3508,다나17b75a
13040,202210,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.01,0.03,0.00,0.00,0.00,0.01,0.02,2062,다나17b75a

In [79]:
df10 = df10.iloc[: , 1:13]

In [80]:
df9 = pd.read_csv('data/JT_SHP_SALES_VARTION_LIST_202209.csv')

In [81]:
df9

,ANALS_YM,CMPNM_NM,SIGNGU_NM,ADSTRD_NM,AREA_NM,MLSFC_NM,SCLAS_NM,JJINHBT_SALES_PRICE_RATE,JJINHBT_SALES_CO_RATE,OTSD_SALES_PRICE_RATE,OTSD_SALES_CO_RATE,ALL_SALES_PRICE_RATE,ALL_SALES_CO_RATE,VARTION_RT,RANK_CO,GID_ID
0,202209,한국맥도날드(유)제주탑동점,제주시,건입동,제주시내,패스트푸드,햄버거,8.79,32.54,0.38,7.22,1.06,16.79,-8.21,13102,다다09b03a
1,202209,모드락탑동점,제주시,건입동,제주시내,한식,단품요리 전문,3.74,5.31,0.62,4.06,0.88,5.24,-2.68,12995,다다09a03a
2,202209,고집돌우럭,제주시,건입동,제주시내,한식,회,0.49,0.17,2.20,3.56,2.08,3.14,-1.85,12825,다다09b03a
3,202209,산지해장국,제주시,건입동,제주시내,한식,해장국,2.50,4.05,0.43,2.83,0.60,3.77,-2.07,12885,다다09b03a
4,202209,산지물,제주시,건입동,제주시내,한식,가정식,2.69,1.79,1.09,2.28,1.22,2.55,-0.66,11857,다다09b03a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13120,202209,엄마손국수,서귀포시,효돈동,서귀포시내,한식,면류,0.03,0.05,0.00,0.00,0.00,0.02,0.02,378,다나17b75a
13121,202209,청마식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.03,0.05,0.00,0.00,0.00,0.02,0.03,270,다나17b73b
13122,202209,바굥식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.03,0.00,0.00,0.00,0.01,0.07,145,다나17b75a
13123,202209,오가네진미식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.03,0.00,0.00,0.00,0.01,-0.01,1560,다나17b75a
13124,202209,또또시,서귀포시,효돈동,서귀포시내,간식,베이커리,0.01,0.03,0.00,0.00,0.00,0.01,-0.01,1561,다나18a73b

In [82]:
df9 = df9.rename(columns={'ANALS_YM' : '분석년월', 'CMPNM_NM' : '음식점명', 'SIGNGU_NM' : '시군구명', 'ADSTRD_NM' : '행정동명',
                   'AREA_NM' : '지역명', 'MLSFC_NM' : '중분류', 'SCLAS_NM' : '소분류', 'JJINHBT_SALES_PRICE_RATE' : '9월현지인매출금액',
                   'JJINHBT_SALES_CO_RATE' : '9월현지인매출수', 'OTSD_SALES_PRICE_RATE' : '9월외지인매출금액', 'OTSD_SALES_CO_RATE' : '9월외지인매출수', 'ALL_SALES_PRICE_RATE' : '9월전체매출금액비율',
                   'ALL_SALES_CO_RATE' : '9월전체매출수비율'})

In [83]:
df9

,분석년월,음식점명,시군구명,행정동명,지역명,중분류,소분류,9월현지인매출금액,9월현지인매출수,9월외지인매출금액,9월외지인매출수,9월전체매출금액비율,9월전체매출수비율,VARTION_RT,RANK_CO,GID_ID
0,202209,한국맥도날드(유)제주탑동점,제주시,건입동,제주시내,패스트푸드,햄버거,8.79,32.54,0.38,7.22,1.06,16.79,-8.21,13102,다다09b03a
1,202209,모드락탑동점,제주시,건입동,제주시내,한식,단품요리 전문,3.74,5.31,0.62,4.06,0.88,5.24,-2.68,12995,다다09a03a
2,202209,고집돌우럭,제주시,건입동,제주시내,한식,회,0.49,0.17,2.20,3.56,2.08,3.14,-1.85,12825,다다09b03a
3,202209,산지해장국,제주시,건입동,제주시내,한식,해장국,2.50,4.05,0.43,2.83,0.60,3.77,-2.07,12885,다다09b03a
4,202209,산지물,제주시,건입동,제주시내,한식,가정식,2.69,1.79,1.09,2.28,1.22,2.55,-0.66,11857,다다09b03a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13120,202209,엄마손국수,서귀포시,효돈동,서귀포시내,한식,면류,0.03,0.05,0.00,0.00,0.00,0.02,0.02,378,다나17b75a
13121,202209,청마식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.03,0.05,0.00,0.00,0.00,0.02,0.03,270,다나17b73b
13122,202209,바굥식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.03,0.00,0.00,0.00,0.01,0.07,145,다나17b75a
13123,202209,오가네진미식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.03,0.00,0.00,0.00,0.01,-0.01,1560,다나17b75a
13124,202209,또또시,서귀포시,효돈동,서귀포시내,간식,베이커리,0.01,0.03,0.00,0.00,0.00,0.01,-0.01,1561,다나18a73b

In [84]:
df9 = df9.iloc[: , [1,7,8,9,10,11,12]]

In [85]:
df9

,음식점명,9월현지인매출금액,9월현지인매출수,9월외지인매출금액,9월외지인매출수,9월전체매출금액비율,9월전체매출수비율
0,한국맥도날드(유)제주탑동점,8.79,32.54,0.38,7.22,1.06,16.79
1,모드락탑동점,3.74,5.31,0.62,4.06,0.88,5.24
2,고집돌우럭,0.49,0.17,2.20,3.56,2.08,3.14
3,산지해장국,2.50,4.05,0.43,2.83,0.60,3.77
4,산지물,2.69,1.79,1.09,2.28,1.22,2.55
...,...,...,...,...,...,...,...
13120,엄마손국수,0.03,0.05,0.00,0.00,0.00,0.02
13121,청마식당,0.03,0.05,0.00,0.00,0.00,0.02
13122,바굥식당,0.02,0.03,0.00,0.00,0.00,0.01
13123,오가네진미식당,0.02,0.03,0.00,0.00,0.00,0.01
13124,또또시,0.01,0.03,0.00,0.00,0.00,0.01

In [86]:
df8 = pd.read_csv('data/JT_SHP_SALES_VARTION_LIST_202208.csv')

In [87]:
df8

,ANALS_YM,CMPNM_NM,SIGNGU_NM,ADSTRD_NM,AREA_NM,MLSFC_NM,SCLAS_NM,JJINHBT_SALES_PRICE_RATE,JJINHBT_SALES_CO_RATE,OTSD_SALES_PRICE_RATE,OTSD_SALES_CO_RATE,ALL_SALES_PRICE_RATE,ALL_SALES_CO_RATE,VARTION_RT,RANK_CO,GID_ID
0,202208,한국맥도날드(유)제주탑동점,제주시,건입동,제주시내,패스트푸드,햄버거,3.44,30.79,0.28,4.82,0.54,8.58,-8.58,13346,다다09b03a
1,202208,모드락탑동점,제주시,건입동,제주시내,한식,단품요리 전문,2.08,6.05,0.35,1.96,0.49,2.56,-2.56,13284,다다09a03a
2,202208,산지물,제주시,건입동,제주시내,한식,가정식,2.65,4.05,0.67,1.52,0.83,1.89,-1.89,13213,다다09b03a
3,202208,고집돌우럭,제주시,건입동,제주시내,한식,회,0.34,0.26,0.90,1.46,0.85,1.29,-1.29,13023,다다09b03a
4,202208,산지해장국,제주시,건입동,제주시내,한식,해장국,0.98,3.38,0.22,1.42,0.28,1.70,-1.70,13177,다다09b03a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13358,202208,오가네진미식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3708,다나17b75a
13359,202208,희나리와돌맹이,서귀포시,효돈동,서귀포시내,한식,단품요리 전문,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3709,다나17b74a
13360,202208,또또시,서귀포시,효돈동,서귀포시내,간식,베이커리,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3710,다나18a73b
13361,202208,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.00,0.05,0.00,0.00,0.00,0.01,-0.01,4552,다나17b75a
13362,202208,커피앤녹두,서귀포시,효돈동,서귀포시내,한식,커피,0.00,0.02,0.00,0.00,0.00,0.00,0.00,3711,다나17b75a

In [88]:
df8 = df8.rename(columns={'ANALS_YM' : '분석년월', 'CMPNM_NM' : '음식점명', 'SIGNGU_NM' : '시군구명', 'ADSTRD_NM' : '행정동명',
                   'AREA_NM' : '지역명', 'MLSFC_NM' : '중분류', 'SCLAS_NM' : '소분류', 'JJINHBT_SALES_PRICE_RATE' : '8월현지인매출금액',
                   'JJINHBT_SALES_CO_RATE' : '8월현지인매출수', 'OTSD_SALES_PRICE_RATE' : '8월외지인매출금액', 'OTSD_SALES_CO_RATE' : '8월외지인매출수', 'ALL_SALES_PRICE_RATE' : '8월전체매출금액비율',
                   'ALL_SALES_CO_RATE' : '8월전체매출수비율'})

In [89]:
df8 = df8.iloc[: , [1,7,8,9,10,11,12]]

In [90]:
df8

,음식점명,8월현지인매출금액,8월현지인매출수,8월외지인매출금액,8월외지인매출수,8월전체매출금액비율,8월전체매출수비율
0,한국맥도날드(유)제주탑동점,3.44,30.79,0.28,4.82,0.54,8.58
1,모드락탑동점,2.08,6.05,0.35,1.96,0.49,2.56
2,산지물,2.65,4.05,0.67,1.52,0.83,1.89
3,고집돌우럭,0.34,0.26,0.90,1.46,0.85,1.29
4,산지해장국,0.98,3.38,0.22,1.42,0.28,1.70
...,...,...,...,...,...,...,...
13358,오가네진미식당,0.00,0.00,0.00,0.00,0.00,0.00
13359,희나리와돌맹이,0.00,0.00,0.00,0.00,0.00,0.00
13360,또또시,0.00,0.00,0.00,0.00,0.00,0.00
13361,666식당,0.00,0.05,0.00,0.00,0.00,0.01
13362,커피앤녹두,0.00,0.02,0.00,0.00,0.00,0.00

In [91]:
# 8, 9, 10월 데이터 합치기

In [92]:
df = pd.merge(df10, df9, on= '음식점명', how= 'left')

In [93]:
df = pd.merge(df, df8, on= '음식점명', how= 'left')

In [94]:
df

,음식점명,시군구명,행정동명,지역명,중분류,소분류,10월현지인매출금액,10월현지인매출수,10월외지인매출금액,10월외지인매출수,...,9월외지인매출금액,9월외지인매출수,9월전체매출금액비율,9월전체매출수비율,8월현지인매출금액,8월현지인매출수,8월외지인매출금액,8월외지인매출수,8월전체매출금액비율,8월전체매출수비율
0,한국맥도날드(유)제주탑동점,제주시,건입동,제주시내,패스트푸드,햄버거,9.99,35.30,0.33,8.41,...,0.38,7.22,1.06,16.79,3.44,30.79,0.28,4.82,0.54,8.58
1,모드락탑동점,제주시,건입동,제주시내,한식,단품요리 전문,3.60,4.72,0.60,4.80,...,0.62,4.06,0.88,5.24,2.08,6.05,0.35,1.96,0.49,2.56
2,산지해장국,제주시,건입동,제주시내,한식,해장국,3.06,4.23,0.49,4.18,...,0.43,2.83,0.60,3.77,0.98,3.38,0.22,1.42,0.28,1.70
3,산지해장국,제주시,건입동,제주시내,한식,해장국,3.06,4.23,0.49,4.18,...,0.43,2.83,0.60,3.77,0.33,1.24,0.06,0.40,0.08,0.52
4,산지해장국,제주시,건입동,제주시내,한식,해장국,3.06,4.23,0.49,4.18,...,0.13,0.86,0.23,1.36,0.98,3.38,0.22,1.42,0.28,1.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13903,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,...,0.00,0.00,0.04,0.26,0.17,0.57,0.00,0.01,0.02,0.09
13904,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,...,0.00,0.00,0.04,0.26,0.01,0.07,0.00,0.00,0.00,0.01
13905,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,...,0.00,0.01,0.00,0.02,0.17,0.57,0.00,0.01,0.02,0.09
13906,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,...,0.00,0.01,0.00,0.02,0.01,0.07,0.00,0.00,0.00,0.01
13907,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.01,0.03,0.00,0.00,...,0.00,0.00,0.00,0.03,0.00,0.05,0.00,0.00,0.00,0.01

In [95]:
df.columns

Index(['음식점명', '시군구명', '행정동명', '지역명', '중분류', '소분류', '10월현지인매출금액', '10월현지인매출수',
       '10월외지인매출금액', '10월외지인매출수', '10월전체매출금액비율', '10월전체매출수비율', '9월현지인매출금액',
       '9월현지인매출수', '9월외지인매출금액', '9월외지인매출수', '9월전체매출금액비율', '9월전체매출수비율',
       '8월현지인매출금액', '8월현지인매출수', '8월외지인매출금액', '8월외지인매출수', '8월전체매출금액비율',
       '8월전체매출수비율'],
      dtype='object')

In [96]:
df.isna().sum()

음식점명             0
시군구명             0
행정동명             0
지역명              0
중분류              0
소분류              0
10월현지인매출금액       0
10월현지인매출수        0
10월외지인매출금액       0
10월외지인매출수        0
10월전체매출금액비율      0
10월전체매출수비율       0
9월현지인매출금액      363
9월현지인매출수       363
9월외지인매출금액      363
9월외지인매출수       363
9월전체매출금액비율     363
9월전체매출수비율      363
8월현지인매출금액      376
8월현지인매출수       376
8월외지인매출금액      376
8월외지인매출수       376
8월전체매출금액비율     376
8월전체매출수비율      376
dtype: int64

In [97]:
df = df.fillna(0)

In [107]:
df['현지인매출금액비율'] = ((df['10월현지인매출금액'] + df['9월현지인매출금액'] + df['8월현지인매출금액']) / 3).round(2)

In [108]:
df['현지인매출수비율'] = ((df['10월현지인매출수'] + df['9월현지인매출수'] + df['8월현지인매출수']) / 3).round(2)

In [109]:
df['외지인매출금액비율'] = ((df['10월외지인매출금액'] + df['9월외지인매출금액'] + df['8월외지인매출금액']) / 3).round(2)

In [110]:
df['외지인매출수비율'] = ((df['10월외지인매출수'] + df['9월외지인매출수'] + df['8월외지인매출수']) / 3).round(2)

In [113]:
df['3개월전체매출금액'] = ((df['10월전체매출금액비율'] + df['9월전체매출금액비율'] + df['8월전체매출금액비율']) / 3).round(2)

In [114]:
df['3개월전체매출수'] = ((df['10월전체매출수비율'] + df['9월전체매출수비율'] + df['8월전체매출수비율']) / 3).round(2)

In [115]:
df

,음식점명,시군구명,행정동명,지역명,중분류,소분류,10월현지인매출금액,10월현지인매출수,10월외지인매출금액,10월외지인매출수,...,8월외지인매출금액,8월외지인매출수,8월전체매출금액비율,8월전체매출수비율,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
0,한국맥도날드(유)제주탑동점,제주시,건입동,제주시내,패스트푸드,햄버거,9.99,35.30,0.33,8.41,...,0.28,4.82,0.54,8.58,7.41,32.88,0.33,6.82,0.87,14.99
1,모드락탑동점,제주시,건입동,제주시내,한식,단품요리 전문,3.60,4.72,0.60,4.80,...,0.35,1.96,0.49,2.56,3.14,5.36,0.52,3.61,0.74,4.49
2,산지해장국,제주시,건입동,제주시내,한식,해장국,3.06,4.23,0.49,4.18,...,0.22,1.42,0.28,1.70,2.18,3.89,0.38,2.81,0.52,3.48
3,산지해장국,제주시,건입동,제주시내,한식,해장국,3.06,4.23,0.49,4.18,...,0.06,0.40,0.08,0.52,1.96,3.17,0.33,2.47,0.46,3.09
4,산지해장국,제주시,건입동,제주시내,한식,해장국,3.06,4.23,0.49,4.18,...,0.22,1.42,0.28,1.70,1.76,3.17,0.28,2.15,0.40,2.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13903,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,...,0.00,0.01,0.02,0.09,0.24,0.49,0.00,0.00,0.02,0.13
13904,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,...,0.00,0.00,0.00,0.01,0.18,0.32,0.00,0.00,0.01,0.10
13905,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,...,0.00,0.01,0.02,0.09,0.07,0.23,0.00,0.01,0.01,0.05
13906,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.08,0.00,0.00,...,0.00,0.00,0.00,0.01,0.02,0.06,0.00,0.00,0.00,0.02
13907,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.01,0.03,0.00,0.00,...,0.00,0.00,0.00,0.01,0.01,0.05,0.00,0.00,0.00,0.02

In [120]:
df2 = df.iloc[ : , [0,1,2,3,4,5,-6,-5,-4,-3,-2,-1]]

In [121]:
df2

,음식점명,시군구명,행정동명,지역명,중분류,소분류,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
0,한국맥도날드(유)제주탑동점,제주시,건입동,제주시내,패스트푸드,햄버거,7.41,32.88,0.33,6.82,0.87,14.99
1,모드락탑동점,제주시,건입동,제주시내,한식,단품요리 전문,3.14,5.36,0.52,3.61,0.74,4.49
2,산지해장국,제주시,건입동,제주시내,한식,해장국,2.18,3.89,0.38,2.81,0.52,3.48
3,산지해장국,제주시,건입동,제주시내,한식,해장국,1.96,3.17,0.33,2.47,0.46,3.09
4,산지해장국,제주시,건입동,제주시내,한식,해장국,1.76,3.17,0.28,2.15,0.40,2.68
...,...,...,...,...,...,...,...,...,...,...,...,...
13903,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.24,0.49,0.00,0.00,0.02,0.13
13904,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.18,0.32,0.00,0.00,0.01,0.10
13905,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.07,0.23,0.00,0.01,0.01,0.05
13906,삼시세끼,서귀포시,효돈동,서귀포시내,한식,가정식,0.02,0.06,0.00,0.00,0.00,0.02
13907,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.01,0.05,0.00,0.00,0.00,0.02

In [ ]:
# 제주도 현지인이 돈을 가장 많이 쓰는 음식점

In [124]:
df2.sort_values('현지인매출금액비율', ascending=False)

,음식점명,시군구명,행정동명,지역명,중분류,소분류,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
1025,한국맥도날드(유)제주노형점,제주시,노형동,제주시내,패스트푸드,햄버거,23.35,98.93,0.64,11.10,2.39,36.92
10355,한국맥도날드(유)제주일도DT점,제주시,일도2동,제주시내,패스트푸드,햄버거,21.39,93.62,0.23,4.09,1.85,29.70
1054,제주늘봄,제주시,노형동,제주시내,한식,가정식,20.17,6.57,0.84,0.76,2.35,2.44
1026,늘봄흑돼지,제주시,노형동,제주시내,한식,돼지고기,17.29,12.75,3.69,5.69,4.80,8.43
8968,한국맥도날드(유)제주시청점,제주시,이도2동,제주시내,패스트푸드,햄버거,15.96,74.49,0.20,4.09,1.40,24.27
...,...,...,...,...,...,...,...,...,...,...,...,...
4870,카페바라크라,서귀포시,송산동,서귀포시내,음료,커피,0.00,0.01,0.00,0.05,0.00,0.05
12061,두꺼비치킨,서귀포시,중앙동,서귀포시내,패스트푸드,치킨,0.00,0.00,0.00,0.02,0.00,0.01
4882,정낭식당,서귀포시,송산동,서귀포시내,한식,단품요리 전문,0.00,0.00,0.02,0.04,0.02,0.04
6378,새별오름식당,제주시,애월읍,애월읍,한식,가정식,0.00,0.00,0.01,0.01,0.00,0.01
6868,칠십리,제주시,연동,제주시내,한식,가정식,0.00,0.00,0.01,0.08,0.01,0.07

In [ ]:
# 제주도 현지인이 자주 가는 음식점

In [125]:
df2.sort_values('현지인매출수비율', ascending=False)

,음식점명,시군구명,행정동명,지역명,중분류,소분류,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
1025,한국맥도날드(유)제주노형점,제주시,노형동,제주시내,패스트푸드,햄버거,23.35,98.93,0.64,11.10,2.39,36.92
10355,한국맥도날드(유)제주일도DT점,제주시,일도2동,제주시내,패스트푸드,햄버거,21.39,93.62,0.23,4.09,1.85,29.70
8968,한국맥도날드(유)제주시청점,제주시,이도2동,제주시내,패스트푸드,햄버거,15.96,74.49,0.20,4.09,1.40,24.27
11878,한국맥도날드(유)서귀포DT점,서귀포시,중앙동,서귀포시내,패스트푸드,햄버거,11.55,49.22,0.33,6.02,1.19,18.90
8388,한국맥도날드(유)제주공항DT점,제주시,용담2동,제주시내,패스트푸드,햄버거,10.64,45.31,0.40,6.97,1.19,18.44
...,...,...,...,...,...,...,...,...,...,...,...,...
13497,오지나(OJINA),제주시,한림읍,한림읍,한식,가정식,0.00,0.00,0.00,0.01,0.00,0.01
584,대게고로케월정점,제주시,구좌읍,구좌읍,한식,분식,0.00,0.00,0.01,0.12,0.01,0.10
5592,진미명가식당,서귀포시,안덕면,안덕면,한식,가정식,0.00,0.00,0.45,0.16,0.43,0.13
595,달식당,제주시,구좌읍,구좌읍,한식,가정식,0.00,0.00,0.05,0.06,0.04,0.05
3161,배짱이만두,서귀포시,동홍동,서귀포시내,한식,만두,0.00,0.00,0.01,0.15,0.01,0.13

In [ ]:
# 관광객(외지인)이 돈을 가장 많이 쓰는 음식점

In [127]:
df2.sort_values('외지인매출금액비율', ascending=False)

,음식점명,시군구명,행정동명,지역명,중분류,소분류,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
5380,(주)오설록 제주점,서귀포시,안덕면,안덕면,음료,차,3.70,5.38,8.27,48.57,8.13,42.58
3386,한화호텔앤드리조트(주)제주지점,제주시,봉개동,제주시내,한식,구내식당/푸드코트,1.00,0.50,5.61,6.63,5.39,5.72
7644,더클리프 (주)씨앤모어,서귀포시,예래동,서귀포시내,양식,커피,3.43,3.87,4.33,19.50,4.34,17.54
5388,주식회사 춘심이네,서귀포시,안덕면,안덕면,한식,가정식,1.41,0.38,4.26,6.06,4.14,5.24
2741,주식회사 토스카나,서귀포시,대천동,서귀포시내,양식,양식,2.67,1.47,4.25,3.63,4.23,3.47
...,...,...,...,...,...,...,...,...,...,...,...,...
10317,웰덤치킨,제주시,일도1동,제주시내,패스트푸드,치킨,0.08,0.11,0.00,0.01,0.01,0.05
10316,속초집,제주시,일도1동,제주시내,한식,단품요리 전문,0.17,0.23,0.00,0.01,0.02,0.08
5238,반올림피자샵제주아라점,제주시,아라동,제주시내,패스트푸드,피자,0.09,0.20,0.00,0.03,0.01,0.08
5239,신산배꼽시계,제주시,아라동,제주시내,한식,단품요리 전문,0.08,0.27,0.00,0.04,0.01,0.12
13907,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.01,0.05,0.00,0.00,0.00,0.02

In [ ]:
# 관광객(외지인)이 자주 가는 음식점

In [126]:
df2.sort_values('외지인매출수비율', ascending=False)

,음식점명,시군구명,행정동명,지역명,중분류,소분류,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
5380,(주)오설록 제주점,서귀포시,안덕면,안덕면,음료,차,3.70,5.38,8.27,48.57,8.13,42.58
8374,롯데리아 제주공항국내선탑승점,제주시,용담2동,제주시내,패스트푸드,햄버거,3.44,14.46,2.09,35.58,2.24,34.37
8376,파리바게뜨제주공항렌트카하우스점,제주시,용담2동,제주시내,간식,베이커리,3.06,6.37,3.89,34.22,3.91,30.92
8375,(주)파리크라상파리바게뜨제주공항탑승점,제주시,용담2동,제주시내,간식,베이커리,3.24,13.97,3.01,33.97,3.09,32.76
8377,오가다 제주공항점,제주시,용담2동,제주시내,음료,차,2.06,9.87,1.72,28.41,1.78,26.89
...,...,...,...,...,...,...,...,...,...,...,...,...
10735,달밤포차,제주시,일도2동,제주시내,한식,가정식,0.09,0.06,0.00,0.00,0.01,0.03
10734,동광고을,제주시,일도2동,제주시내,한식,가정식,0.18,0.13,0.00,0.00,0.01,0.04
10733,복돈갈비,제주시,일도2동,제주시내,한식,갈비,0.08,0.02,0.00,0.00,0.01,0.00
10732,세남매,제주시,일도2동,제주시내,한식,단품요리 전문,0.10,0.10,0.00,0.00,0.01,0.04
13907,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.01,0.05,0.00,0.00,0.00,0.02

In [ ]:
# 3개월동안 사람들이 많이 방문한 음식점

In [128]:
df2.sort_values('3개월전체매출수', ascending=False)

,음식점명,시군구명,행정동명,지역명,중분류,소분류,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
5380,(주)오설록 제주점,서귀포시,안덕면,안덕면,음료,차,3.70,5.38,8.27,48.57,8.13,42.58
1025,한국맥도날드(유)제주노형점,제주시,노형동,제주시내,패스트푸드,햄버거,23.35,98.93,0.64,11.10,2.39,36.92
8374,롯데리아 제주공항국내선탑승점,제주시,용담2동,제주시내,패스트푸드,햄버거,3.44,14.46,2.09,35.58,2.24,34.37
8375,(주)파리크라상파리바게뜨제주공항탑승점,제주시,용담2동,제주시내,간식,베이커리,3.24,13.97,3.01,33.97,3.09,32.76
8376,파리바게뜨제주공항렌트카하우스점,제주시,용담2동,제주시내,간식,베이커리,3.06,6.37,3.89,34.22,3.91,30.92
...,...,...,...,...,...,...,...,...,...,...,...,...
7448,인생과삶,제주시,연동,제주시내,한식,단품요리 전문,0.03,0.01,0.00,0.00,0.01,0.00
7447,마리나,제주시,연동,제주시내,한식,단품요리 전문,0.00,0.00,0.05,0.00,0.05,0.00
2705,가파도상동식당,서귀포시,대정읍,대정읍,한식,가정식,0.00,0.00,0.00,0.00,0.00,0.00
4227,애플웨딩식당,서귀포시,서홍동,서귀포시내,부페,뷔페,0.63,0.01,0.00,0.00,0.04,0.00
7457,뭉크,제주시,연동,제주시내,한식,단품요리 전문,0.00,0.00,0.00,0.00,0.00,0.00

In [ ]:
# 3개월동안 사람들이 많이 소비한 음식점

In [129]:
df2.sort_values('3개월전체매출금액', ascending=False)

,음식점명,시군구명,행정동명,지역명,중분류,소분류,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
5380,(주)오설록 제주점,서귀포시,안덕면,안덕면,음료,차,3.70,5.38,8.27,48.57,8.13,42.58
3386,한화호텔앤드리조트(주)제주지점,제주시,봉개동,제주시내,한식,구내식당/푸드코트,1.00,0.50,5.61,6.63,5.39,5.72
1026,늘봄흑돼지,제주시,노형동,제주시내,한식,돼지고기,17.29,12.75,3.69,5.69,4.80,8.43
7644,더클리프 (주)씨앤모어,서귀포시,예래동,서귀포시내,양식,커피,3.43,3.87,4.33,19.50,4.34,17.54
2741,주식회사 토스카나,서귀포시,대천동,서귀포시내,양식,양식,2.67,1.47,4.25,3.63,4.23,3.47
...,...,...,...,...,...,...,...,...,...,...,...,...
7435,스탠딩스테이크 신제주점,제주시,연동,제주시내,양식,스테이크,0.04,0.08,0.00,0.00,0.00,0.03
7438,맵지,제주시,연동,제주시내,한식,단품요리 전문,0.03,0.06,0.00,0.00,0.00,0.02
7439,댜오위다오,제주시,연동,제주시내,한식,단품요리 전문,0.04,0.12,0.00,0.01,0.00,0.03
7442,제주에살다컴퍼니,제주시,연동,제주시내,한식,단품요리 전문,0.01,0.02,0.00,0.01,0.00,0.01
13907,666식당,서귀포시,효돈동,서귀포시내,한식,가정식,0.01,0.05,0.00,0.00,0.00,0.02

In [130]:
df.columns

Index(['음식점명', '시군구명', '행정동명', '지역명', '중분류', '소분류', '10월현지인매출금액', '10월현지인매출수',
       '10월외지인매출금액', '10월외지인매출수', '10월전체매출금액비율', '10월전체매출수비율', '9월현지인매출금액',
       '9월현지인매출수', '9월외지인매출금액', '9월외지인매출수', '9월전체매출금액비율', '9월전체매출수비율',
       '8월현지인매출금액', '8월현지인매출수', '8월외지인매출금액', '8월외지인매출수', '8월전체매출금액비율',
       '8월전체매출수비율', '현지인매출금액비율', '현지인매출수비율', '외지인매출금액비율', '외지인매출수비율',
       '3개월전체매출금액', '3개월전체매출수'],
      dtype='object')

In [ ]:
# 10월에 현지인이 가장 많이 소비한 음식점

In [133]:
df.loc[df['10월현지인매출수'] == df['10월현지인매출수'].max()]

,음식점명,시군구명,행정동명,지역명,중분류,소분류,10월현지인매출금액,10월현지인매출수,10월외지인매출금액,10월외지인매출수,...,8월외지인매출금액,8월외지인매출수,8월전체매출금액비율,8월전체매출수비율,현지인매출금액비율,현지인매출수비율,외지인매출금액비율,외지인매출수비율,3개월전체매출금액,3개월전체매출수
1025,한국맥도날드(유)제주노형점,제주시,노형동,제주시내,패스트푸드,햄버거,29.93,100.76,0.71,14.61,...,0.43,6.43,1.36,19.27,23.35,98.93,0.64,11.1,2.39,36.92