In [13]:
import pandas as pd
import numpy as np

In [14]:
df10 = pd.read_csv('data/JT_MT_ACCTO_TRRSRT_SCCNT_LIST_202210.csv')

In [15]:
df10

,CL_CD,CL_NM,AREA_NM,ADDR,BASE_YEAR,ALL_TOTAL_CO,JAN_VIEWS_CO,FEB_VIEWS_CO,MAR_VIEWS_CO,APR_VIEWS_CO,MAY_VIEWS_CO,JUN_VIEWS_CO,JULY_VIEWS_CO,AUG_VIEWS_CO,SEP_VIEWS_CO,OCT_VIEWS_CO,NOV_VIEWS_CO,DEC_VIEWS_CO
0,c1,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,2022,97,0,0,0,0,0,0,0,0,0,97,0,0
1,c1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,2022,641,0,0,0,0,0,0,0,0,0,641,0,0
2,c1,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,2022,805,0,0,0,0,0,0,0,0,0,805,0,0
3,c1,관광지,1111,제주특별자치도 서귀포시 성산읍 일출로 284-12,2022,1,0,0,0,0,0,0,0,0,0,1,0,0
4,c1,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),2022,93,0,0,0,0,0,0,0,0,0,93,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3854,c4,음식점,흑돼지촌,제주특별자치도 제주시 한림읍 한림상로 62,2022,44,0,0,0,0,0,0,0,0,0,44,0,0
3855,c4,음식점,흑돼지킹생구이전문점,제주특별자치도 제주시 도령로11길 26-9,2022,70,0,0,0,0,0,0,0,0,0,70,0,0
3856,c4,음식점,흑소랑,제주특별자치도 제주시 연북로 631,2022,68,0,0,0,0,0,0,0,0,0,68,0,0
3857,c4,음식점,흑염소마루,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,2022,82,0,0,0,0,0,0,0,0,0,82,0,0
3858,c4,음식점,흑한우명품관,제주특별자치도 서귀포시 일주동로 8421,2022,89,0,0,0,0,0,0,0,0,0,89,0,0

In [22]:
df10 = df10.rename(columns={'CL_NM' : '분류', 'AREA_NM' : '관광지명', 'ADDR' : '주소', 'BASE_YEAR' : '기준년도',
                   'ALL_TOTAL_CO' : '전체조회수', 'JAN_VIEWS_CO' : '1월', 'FEB_VIEWS_CO' : '2월', 'MAR_VIEWS_CO' : '3월',
                   'APR_VIEWS_CO' : '4월', 'MAY_VIEWS_CO' : '5월', 'JUN_VIEWS_CO' : '6월', 'JULY_VIEWS_CO' : '7월',
                   'AUG_VIEWS_CO' : '8월', 'SEP_VIEWS_CO' : '9월', 'OCT_VIEWS_CO' : '10월', 'NOV_VIEWS_CO' : '11월',
                   'DEC_VIEWS_CO' : '12월'})

In [24]:
df10 = df10[['분류','관광지명','주소','기준년도','10월']]

In [25]:
df10

       분류            관광지명                             주소  기준년도  10월
0     관광지  (주)제주해양레저 투명카약       제주특별자치도 제주시 애월읍 애월로1길 22  2022   97
1     관광지     1100고지(휴게소)        제주특별자치도 서귀포시 1100로 1555  2022  641
2     관광지        1100고지습지         제주특별자치도 서귀포시 색달동 산 1-2  2022  805
3     관광지            1111    제주특별자치도 서귀포시 성산읍 일출로 284-12  2022    1
4     관광지          1112도로      제주특별자치도 제주시 명림로 584 (봉개동)  2022   93
...   ...             ...                            ...   ...  ...
3854  음식점            흑돼지촌        제주특별자치도 제주시 한림읍 한림상로 62  2022   44
3855  음식점      흑돼지킹생구이전문점        제주특별자치도 제주시 도령로11길 26-9  2022   70
3856  음식점             흑소랑            제주특별자치도 제주시 연북로 631  2022   68
3857  음식점           흑염소마루  제주특별자치도 서귀포시 남원읍 태위로663번길 1-1  2022   82
3858  음식점          흑한우명품관         제주특별자치도 서귀포시 일주동로 8421  2022   89

[3859 rows x 5 columns]

In [53]:
df9 = pd.read_csv('data/JT_MT_ACCTO_TRRSRT_SCCNT_LIST_202209.csv')

In [54]:
df9 = df9.rename(columns={'CL_NM' : '분류', 'AREA_NM' : '관광지명', 'ADDR' : '주소', 'BASE_YEAR' : '기준년도',
                   'ALL_TOTAL_CO' : '전체조회수', 'JAN_VIEWS_CO' : '1월', 'FEB_VIEWS_CO' : '2월', 'MAR_VIEWS_CO' : '3월',
                   'APR_VIEWS_CO' : '4월', 'MAY_VIEWS_CO' : '5월', 'JUN_VIEWS_CO' : '6월', 'JULY_VIEWS_CO' : '7월',
                   'AUG_VIEWS_CO' : '8월', 'SEP_VIEWS_CO' : '9월', 'OCT_VIEWS_CO' : '10월', 'NOV_VIEWS_CO' : '11월',
                   'DEC_VIEWS_CO' : '12월'})

In [55]:
df9 = df9[['관광지명','9월']]

In [56]:
df9

                관광지명   9월
0     (주)제주해양레저 투명카약  104
1        1100고지(휴게소)  400
2           1100고지습지  709
3             1112도로   68
4           4·3해원방사탑   75
...              ...  ...
3840            흑돼지촌   44
3841      흑돼지킹생구이전문점   53
3842             흑소랑   88
3843           흑염소마루   58
3844          흑한우명품관  109

[3845 rows x 2 columns]

In [57]:
df8 = pd.read_csv('data/JT_MT_ACCTO_TRRSRT_SCCNT_LIST_202208.csv')

In [58]:
df8 = df8.rename(columns={'CL_NM' : '분류', 'AREA_NM' : '관광지명', 'ADDR' : '주소', 'BASE_YEAR' : '기준년도',
                   'ALL_TOTAL_CO' : '전체조회수', 'JAN_VIEWS_CO' : '1월', 'FEB_VIEWS_CO' : '2월', 'MAR_VIEWS_CO' : '3월',
                   'APR_VIEWS_CO' : '4월', 'MAY_VIEWS_CO' : '5월', 'JUN_VIEWS_CO' : '6월', 'JULY_VIEWS_CO' : '7월',
                   'AUG_VIEWS_CO' : '8월', 'SEP_VIEWS_CO' : '9월', 'OCT_VIEWS_CO' : '10월', 'NOV_VIEWS_CO' : '11월',
                   'DEC_VIEWS_CO' : '12월'})

In [59]:
df8 = df8[['관광지명','8월']]

In [ ]:
# 8, 9, 10월 데이터 합치기

In [61]:
df = pd.merge(df10, df9, on= '관광지명', how= 'left')

In [62]:
df = pd.merge(df, df8, on= '관광지명', how= 'left')

In [63]:
df

,분류,관광지명,주소,기준년도,10월,9월,8월
0,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,2022,97,104.0,161.0
1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,2022,641,400.0,457.0
2,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,2022,805,709.0,814.0
3,관광지,1111,제주특별자치도 서귀포시 성산읍 일출로 284-12,2022,1,NaN,NaN
4,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),2022,93,68.0,83.0
...,...,...,...,...,...,...,...
3854,음식점,흑돼지촌,제주특별자치도 제주시 한림읍 한림상로 62,2022,44,44.0,33.0
3855,음식점,흑돼지킹생구이전문점,제주특별자치도 제주시 도령로11길 26-9,2022,70,53.0,50.0
3856,음식점,흑소랑,제주특별자치도 제주시 연북로 631,2022,68,88.0,77.0
3857,음식점,흑염소마루,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,2022,82,58.0,49.0
3858,음식점,흑한우명품관,제주특별자치도 서귀포시 일주동로 8421,2022,89,109.0,102.0

In [65]:
df.isna().sum()

분류       0
관광지명     0
주소       0
기준년도     0
10월      0
9월      32
8월      33
dtype: int64

In [ ]:
# nan값은 0으로 채워준다

In [67]:
df = df.fillna(0)

In [71]:
df['분류'].unique()

array(['관광지', '쇼핑', '숙박', '음식점'], dtype=object)

In [72]:
df['관광지명'].nunique()

3859

In [73]:
df['기준년도'].nunique()

1

In [75]:
# 기준년도는 필요 없으니 삭제한다
df = df.drop('기준년도', axis= 1 )

In [77]:
df['전체조회수'] = df['8월'] + df['9월'] + df['10월']

In [78]:
df

,분류,관광지명,주소,10월,9월,8월,전체조회수
0,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,97,104.0,161.0,362.0
1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,641,400.0,457.0,1498.0
2,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,805,709.0,814.0,2328.0
3,관광지,1111,제주특별자치도 서귀포시 성산읍 일출로 284-12,1,0.0,0.0,1.0
4,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),93,68.0,83.0,244.0
...,...,...,...,...,...,...,...
3854,음식점,흑돼지촌,제주특별자치도 제주시 한림읍 한림상로 62,44,44.0,33.0,121.0
3855,음식점,흑돼지킹생구이전문점,제주특별자치도 제주시 도령로11길 26-9,70,53.0,50.0,173.0
3856,음식점,흑소랑,제주특별자치도 제주시 연북로 631,68,88.0,77.0,233.0
3857,음식점,흑염소마루,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,82,58.0,49.0,189.0
3858,음식점,흑한우명품관,제주특별자치도 서귀포시 일주동로 8421,89,109.0,102.0,300.0

In [83]:
df['평균조회수'] = (df['전체조회수'] / 3).round()

In [84]:
df

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
0,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,97,104.0,161.0,362.0,121.0
1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,641,400.0,457.0,1498.0,499.0
2,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,805,709.0,814.0,2328.0,776.0
3,관광지,1111,제주특별자치도 서귀포시 성산읍 일출로 284-12,1,0.0,0.0,1.0,0.0
4,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),93,68.0,83.0,244.0,81.0
...,...,...,...,...,...,...,...,...
3854,음식점,흑돼지촌,제주특별자치도 제주시 한림읍 한림상로 62,44,44.0,33.0,121.0,40.0
3855,음식점,흑돼지킹생구이전문점,제주특별자치도 제주시 도령로11길 26-9,70,53.0,50.0,173.0,58.0
3856,음식점,흑소랑,제주특별자치도 제주시 연북로 631,68,88.0,77.0,233.0,78.0
3857,음식점,흑염소마루,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,82,58.0,49.0,189.0,63.0
3858,음식점,흑한우명품관,제주특별자치도 서귀포시 일주동로 8421,89,109.0,102.0,300.0,100.0

In [ ]:
# 전체 조회수가 높은 관광지

In [97]:
df.loc[ df['전체조회수'] == df['전체조회수'].max() ]

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
377,관광지,비자림,제주특별자치도 제주시 구좌읍 비자숲길 55,10979,9288.0,10699.0,30966.0,10322.0

In [ ]:
# 분류별 전체조회수가 높은 관광지 ['관광지', '쇼핑', '숙박', '음식점']

In [90]:
tourism_df = df.loc[ df['분류'] == '관광지' ]

In [92]:
shopping_df = df.loc[ df['분류'] == '쇼핑' ]

In [95]:
tourism_df.loc[ tourism_df['전체조회수'] == tourism_df['전체조회수'].max() ]

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
377,관광지,비자림,제주특별자치도 제주시 구좌읍 비자숲길 55,10979,9288.0,10699.0,30966.0,10322.0

In [96]:
shopping_df.loc[ shopping_df['전체조회수'] == shopping_df['전체조회수'].max() ]

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
1212,쇼핑,제주민속오일시장,제주특별자치도 제주시 오일장서길 26,5039,3423.0,2337.0,10799.0,3600.0

In [ ]:
# 제주도 주소로 관광지 검색하기

In [136]:
df = df.sort_values('평균조회수', ascending=False)

In [131]:
df['주소'].str.contains('서귀포시').sum()

1477

In [137]:
df.loc[ df['주소'].str.contains('서귀포시') ]

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
478,관광지,성산일출봉(UNESCO 세계자연유산),제주특별자치도 서귀포시 성산읍 일출로 284-12,11845,8708.0,6826.0,27379.0,9126.0
957,관광지,천지연폭포,제주특별자치도 서귀포시 남성중로 2-15,4340,3868.0,4847.0,13055.0,4352.0
470,관광지,섭지코지,제주특별자치도 서귀포시 성산읍 섭지코지로 107,4252,3347.0,3490.0,11089.0,3696.0
675,관광지,용머리해안,제주특별자치도 서귀포시 안덕면 사계리,4787,2057.0,3117.0,9961.0,3320.0
523,관광지,쇠소깍,제주특별자치도 서귀포시 쇠소깍로 128,4649,1595.0,2724.0,8968.0,2989.0
...,...,...,...,...,...,...,...,...
251,관광지,마린파크,제주특별자치도 서귀포시 안덕면 화순중앙로 132,3,1.0,0.0,4.0,1.0
250,관광지,마라도잠수함,제주특별자치도 서귀포시 안덕면 형제해안로 13,2,0.0,0.0,2.0,1.0
2231,음식점,갓포하루,제주특별자치도 서귀포시 중문상로 46 1층,1,0.0,1.0,2.0,1.0
1681,숙박,숲속의궁전,제주특별자치도 서귀포시 염돈로28번길 46,1,0.0,0.0,1.0,0.0
3,관광지,1111,제주특별자치도 서귀포시 성산읍 일출로 284-12,1,0.0,0.0,1.0,0.0

In [138]:
df['주소'].str.contains('제주시').sum()

2374

In [139]:
df.loc[ df['주소'].str.contains('제주시') ]

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
377,관광지,비자림,제주특별자치도 제주시 구좌읍 비자숲길 55,10979,9288.0,10699.0,30966.0,10322.0
393,관광지,사려니숲길,제주특별자치도 제주시 조천읍 교래리 산 137-1,10374,8501.0,10873.0,29748.0,9916.0
682,관광지,우도(해양도립공원),제주특별자치도 제주시 우도면 삼양고수물길 1,10117,7765.0,8417.0,26299.0,8766.0
259,관광지,만장굴,제주특별자치도 제주시 구좌읍 만장굴길 182,6757,5999.0,9713.0,22469.0,7490.0
427,관광지,새별오름,제주특별자치도 제주시 애월읍 봉성리 산 59-8,9905,6028.0,4071.0,20004.0,6668.0
...,...,...,...,...,...,...,...,...
3217,음식점,오쿠다,제주특별자치도 제주시 구남동4길 45,1,0.0,0.0,1.0,0.0
1555,숙박,바르게스트하우스,제주특별자치도 제주시 한림읍 협재1길 17-1,1,0.0,0.0,1.0,0.0
617,관광지,어승생승마장 Horseland Jeju,제주특별자치도 제주시 1100로 2659 (노형동),1,0.0,0.0,1.0,0.0
358,관광지,북돌아진오름,제주특별자치도 제주시 애월읍 봉성리 산 41,1,0.0,0.0,1.0,0.0
214,관광지,동검은이오름(거미오름),제주특별자치도 제주시 구좌읍 종달리 산 70,1,0.0,0.0,1.0,0.0

In [ ]:
# 조회수가 제일 높은 10곳(조회수가 제일 높은 10곳의 월별 조회수 차트로 표현)

In [141]:
df.head(10)

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
377,관광지,비자림,제주특별자치도 제주시 구좌읍 비자숲길 55,10979,9288.0,10699.0,30966.0,10322.0
393,관광지,사려니숲길,제주특별자치도 제주시 조천읍 교래리 산 137-1,10374,8501.0,10873.0,29748.0,9916.0
478,관광지,성산일출봉(UNESCO 세계자연유산),제주특별자치도 서귀포시 성산읍 일출로 284-12,11845,8708.0,6826.0,27379.0,9126.0
682,관광지,우도(해양도립공원),제주특별자치도 제주시 우도면 삼양고수물길 1,10117,7765.0,8417.0,26299.0,8766.0
259,관광지,만장굴,제주특별자치도 제주시 구좌읍 만장굴길 182,6757,5999.0,9713.0,22469.0,7490.0
427,관광지,새별오름,제주특별자치도 제주시 애월읍 봉성리 산 59-8,9905,6028.0,4071.0,20004.0,6668.0
957,관광지,천지연폭포,제주특별자치도 서귀포시 남성중로 2-15,4340,3868.0,4847.0,13055.0,4352.0
1065,관광지,함덕해수욕장,제주특별자치도 제주시 조천읍 조함해안로 519-10,2645,2269.0,7057.0,11971.0,3990.0
1086,관광지,협재해수욕장,제주특별자치도 제주시 한림읍 한림로 329-10,2741,2338.0,6532.0,11611.0,3870.0
470,관광지,섭지코지,제주특별자치도 서귀포시 성산읍 섭지코지로 107,4252,3347.0,3490.0,11089.0,3696.0

In [ ]:
# 월별 조회수가 가장 많은 곳

In [143]:
df.loc[ df['10월'] == df['10월'].max() ]

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
478,관광지,성산일출봉(UNESCO 세계자연유산),제주특별자치도 서귀포시 성산읍 일출로 284-12,11845,8708.0,6826.0,27379.0,9126.0

In [144]:
df.loc[ df['9월'] == df['9월'].max() ]

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
377,관광지,비자림,제주특별자치도 제주시 구좌읍 비자숲길 55,10979,9288.0,10699.0,30966.0,10322.0

In [145]:
df.loc[ df['8월'] == df['8월'].max() ]

,분류,관광지명,주소,10월,9월,8월,전체조회수,평균조회수
393,관광지,사려니숲길,제주특별자치도 제주시 조천읍 교래리 산 137-1,10374,8501.0,10873.0,29748.0,9916.0